/* tslint:disable */
/* eslint-disable */
/**
 * This file was originally intended to be auto-generated by Payload.
 * Hand-written to match the Homepage global schema.
 */

export interface Config {
  globals: {
    'site-settings': SiteSettings
  }
  collections: {
    users: User
    media: Media
    pages: Page
  }
}

/* ── Collections ────────────────────────────────────────────────────── */

export interface User {
  id: string
  email: string
  createdAt: string
  updatedAt: string
}

export interface Media {
  id: string
  alt: string
  url?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  sizes?: {
    thumbnail?: MediaSize | null
    card?: MediaSize | null
    hero?: MediaSize | null
  }
  createdAt: string
  updatedAt: string
}

export interface MediaSize {
  url?: string | null
  width?: number | null
  height?: number | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
}

export interface Page {
  id: string
  title: string
  slug: string
  meta?: {
    title?: string | null
    description?: string | null
    image?: string | Media | null
  }
  layout?: (HeroBlock | ContentWithImageBlock | CTABlock | FeaturesBlock | TestimonialsBlock)[]
  createdAt: string
  updatedAt: string
}

/* ── Blocks ─────────────────────────────────────────────────────────── */

export interface HeroBlock {
  blockType: 'hero'
  blockName?: string | null
  heading: string
  subheading?: string | null
  image?: string | Media | null
  ctaText?: string | null
  ctaLink?: string | null
  style?: 'default' | 'centered' | 'split' | null
}

export interface ContentWithImageBlock {
  blockType: 'contentWithImage'
  blockName?: string | null
  heading: string
  content: unknown // Lexical rich text
  image: string | Media
  imagePosition?: 'left' | 'right' | null
}

export interface CTABlock {
  blockType: 'cta'
  blockName?: string | null
  heading: string
  description?: string | null
  buttonText: string
  buttonLink: string
  style?: 'default' | 'banner' | 'minimal' | null
}

export interface FeaturesBlock {
  blockType: 'features'
  blockName?: string | null
  heading: string
  subtitle?: string | null
  features: {
    icon?: string | null
    title: string
    description: string
  }[]
}

export interface TestimonialsBlock {
  blockType: 'testimonials'
  blockName?: string | null
  heading?: string | null
  testimonials: {
    quote: string
    author: string
    role?: string | null
    company?: string | null
    avatar?: string | Media | null
  }[]
}

/* ── Site Settings Global ───────────────────────────────────────────── */

export interface SiteSettings {
  colors: {
    accentColor?: string | null
    accentHover?: string | null
    surfaceColor?: string | null
    surfaceAlt?: string | null
    textColor?: string | null
    textMuted?: string | null
    textDim?: string | null
    borderColor?: string | null
  }
  fonts: {
    headingFont?: 'inter' | 'dm-sans' | 'space-grotesk' | 'outfit' | 'manrope' | null
    monoFont?: 'jetbrains-mono' | 'fira-code' | 'ibm-plex-mono' | null
  }
  brand: {
    logoText?: string | null
    siteTitle?: string | null
    siteDescription?: string | null
  }
}
